language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"

addons:
    apt:
        packages:
        - jpegoptim
        - optipng
        - pngcrush
        - graphicsmagick
        - nodejs
        - npm

before_install:
  - "node -v"
  - "npm -v"
  - "npm install -g less requirejs promise autoprefixer postcss-cli"

install:
  - "pip install webtest mock coverage nose-cov flake8 python-coveralls --use-mirrors"
  - "pip install -e . --use-mirrors"

before_script: "flake8"

script:  "nosetests"

after_success:
  - coveralls
