language: python
sudo: false

python:
  - "2.7"
  - "3.5"

addons:
    apt:
        packages:
        - jpegoptim
        - optipng
        - pngcrush
        - graphicsmagick

before_install:
  - "nvm install 4.2.1"
  - "nvm use 4.2.1"
  - "node -v"
  - "npm -v"
  - "npm install -g less requirejs autoprefixer postcss-cli"

install:
  - "pip install webtest mock coverage nose-cov flake8 python-coveralls"
  - "pip install -e ."

before_script: "flake8"

script:  "nosetests"

after_success:
  - coveralls
